/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package katarak;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.time.LocalDateTime;
import katarak.utility.Koneksi;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class MainWelPage extends javax.swing.JFrame {
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    String sql;
    int posX=0,posY=0;
    
    /**
     * Creates new form MainWelPage
     */
    public MainWelPage() {
        initComponents();
        Koneksi DB = new Koneksi();
        DB.config();
        con = DB.con;
        LblNamaUsr.removeAll();
        loadNama();
        loadMK();
        
        this.pack();
        this.setLocationRelativeTo(null);
        
        this.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                posX=e.getX();
                posY=e.getY();
            }
        });
        
        this.addMouseMotionListener(new MouseAdapter() {
            public void mouseDragged(MouseEvent evt) {
                setLocation(evt.getXOnScreen()-posX,evt.getYOnScreen()-posY);
            }
        });
        
        CmbMatKul.addFocusListener(getFocusListenerCmb());
        CmbDataMhs.addFocusListener(getFocusListenerMhs());
        
        ActionListener updateClockMK = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if(DB.getActivePanel()=="pilihmk") {
                    PnlPilihMK.setVisible(true);
                    PnlData.setVisible(false);
                } else {
                    PnlPilihMK.setVisible(false);
                    PnlData.setVisible(true);
                }
                if (DB.getRefreshCmb()=="yes") {
                    loadMhsCmb();
                    DB.setRefreshCmb("no");
                }
                loadMhsTbl();
                String mkfin = DB.getSelectedMK();
                OutputNamaMK.setText(mkfin);
            }
        };
        Timer tmk = new Timer(500, updateClockMK);
        tmk.start();
    }
    
    private FocusListener getFocusListenerCmb() {
        return new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent arg0) {
                loadMK();
            }
        };
    }
    
    private FocusListener getFocusListenerMhs() {
        return new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent arg0) {
                loadMhsCmb();
            }
        };
    }
    
    private void loadMK() {
        String mk = null;
        try {
            Koneksi nip = new Koneksi();
            String hashfin = nip.getSession();
            String showmk = "SELECT namamk FROM detailmatakuliah WHERE otoritas='"+hashfin+"' ORDER BY nama ASC";
            ps = con.prepareStatement(showmk);
            rs = ps.executeQuery(showmk);
            CmbMatKul.removeAllItems();
            while(rs.next()) {
                mk = rs.getString("namamk");
                CmbMatKul.addItem(mk);
            }
            if(mk==null) {
                CmbMatKul.addItem("Tidak ada mata kuliah");
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void loadNama() {
        try {
            Koneksi nama = new Koneksi();
            String hashfin = nama.getSession();
            String shownama = "SELECT nama FROM dosen WHERE nip='"+hashfin+"'";
            ps = con.prepareStatement(shownama);
            rs = ps.executeQuery(shownama);
            while(rs.next()) {
                String user = rs.getString("nama");
                LblNamaUsr.setText(user);
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        BtnFgtPass = new javax.swing.JButton();
        BtnNewMhs = new javax.swing.JButton();
        BtnNewMK = new javax.swing.JButton();
        BtnHome = new javax.swing.JButton();
        BtnNewAcc = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LblNamaUsr = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        PnlPilihMK = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CmbMatKul = new javax.swing.JComboBox<>();
        BtnTmbMK = new javax.swing.JButton();
        BtnEdit = new javax.swing.JButton();
        PicSamrat = new javax.swing.JLabel();
        BtnLihat = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        PnlData = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblDataMhs = new javax.swing.JTable();
        BtnEditMK = new javax.swing.JButton();
        BtnHpsMK = new javax.swing.JButton();
        CmbDataMhs = new javax.swing.JComboBox<>();
        BtnBukaMhs = new javax.swing.JButton();
        BtnTambahMhs = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        OutputNamaMK = new javax.swing.JTextField();
        LblJamSelesai = new javax.swing.JLabel();
        LblSKS = new javax.swing.JLabel();
        LblHari = new javax.swing.JLabel();
        LblJamMulai = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        BtnMin = new javax.swing.JButton();
        BtnLogOut = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/katarak/images/appicon.png")).getImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnFgtPass.setBackground(new java.awt.Color(51, 51, 51));
        BtnFgtPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/katarak/images/icons8-password-24.png"))); // NOI18N
        BtnFgtPass.setToolTipText("Lupa Password");
        BtnFgtPass.setBorderPainted(false);
        BtnFgtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFgtPassActionPerformed(evt);
            }
        });
        jPanel5.add(BtnFgtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 50, -1));

        BtnNewMhs.setBackground(new java.awt.Color(51, 51, 51));
        BtnNewMhs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/katarak/images/icons8-add-user-group-man-man-24.png"))); // NOI18N
        BtnNewMhs.setToolTipText("Tambah Mahasiswa");
        BtnNewMhs.setBorderPainted(false);
        BtnNewMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNewMhsActionPerformed(evt);
            }
        });
        jPanel5.add(BtnNewMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 50, -1));

        BtnNewMK.setBackground(new java.awt.Color(51, 51, 51));
        BtnNewMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/katarak/images/icons8-add-property-24.png"))); // NOI18N
        BtnNewMK.setToolTipText("Tambah Mata Kuliah");
        BtnNewMK.setBorderPainted(false);
        BtnNewMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNewMKActionPerformed(evt);
            }
        });
        jPanel5.add(BtnNewMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 50, -1));

        BtnHome.setBackground(new java.awt.Color(51, 51, 51));
        BtnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/katarak/images/icons8-home-24.png"))); // NOI18N
        BtnHome.setToolTipText("Beranda");
        BtnHome.setBorderPainted(false);
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });
        jPanel5.add(BtnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 50, -1));

        BtnNewAcc.setBackground(new java.awt.Color(51, 51, 51));
        BtnNewAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/katarak/images/icons8-account-24.png"))); // NOI18N
        BtnNewAcc.setToolTipText("Tambahkan Akun");
        BtnNewAcc.setBorderPainted(false);
        BtnNewAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNewAccActionPerformed(evt);
            }
        });
        jPanel5.add(BtnNewAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 50, -1));

        jPanel7.setBackground(new java.awt.Color(37, 37, 37));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 50, 110));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 30, 10));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/katarak/images/icons8-search-client-24.png"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 50, 600));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Quicksand", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("rak");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 204, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Quicksand", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("kata");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 50, 40));

        jLabel6.setFont(new java.awt.Font("Quicksand", 1, 6)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("temuKAn daTa mahasiswA yang mengontRAK");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 160, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 800, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Quicksand", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Selamat datang!");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        LblNamaUsr.setFont(new java.awt.Font("Quicksand", 0, 24)); // NOI18N
        LblNamaUsr.setForeground(new java.awt.Color(51, 51, 51));
        LblNamaUsr.setText("Prof. Dr. Test User, S.T, M.T");
        jPanel2.add(LblNamaUsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 730, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/katarak/images/icons8-mortarboard-100.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 800, 180));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlPilihMK.setBackground(new java.awt.Color(255, 255, 255));
        PnlPilihMK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Silahkan memilih Mata Kuliah");
        PnlPilihMK.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        CmbMatKul.setBackground(new java.awt.Color(204, 204, 204));
        CmbMatKul.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        CmbMatKul.setForeground(new java.awt.Color(51, 51, 51));
        PnlPilihMK.add(CmbMatKul, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 330, -1));

        BtnTmbMK.setBackground(new java.awt.Color(102, 255, 0));
        BtnTmbMK.setFont(new java.awt.Font("Quicksand Medium", 1, 12)); // NOI18N
        BtnTmbMK.setForeground(new java.awt.Color(51, 51, 51));
        BtnTmbMK.setText("+ Tambah mata kuliah");
        BtnTmbMK.setBorderPainted(false);
        BtnTmbMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTmbMKActionPerformed(evt);
            }
        });
        PnlPilihMK.add(BtnTmbMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        BtnEdit.setBackground(new java.awt.Color(0, 51, 102));
        BtnEdit.setFont(new java.awt.Font("Quicksand Medium", 1, 12)); // NOI18N
        BtnEdit.setForeground(new java.awt.Color(255, 255, 255));
        BtnEdit.setText("Edit Mata Kuliah");
        BtnEdit.setBorderPainted(false);
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });
        PnlPilihMK.add(BtnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, 30));

        PicSamrat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/katarak/images/biro-umum-1-removebg-preview.png"))); // NOI18N
        PnlPilihMK.add(PicSamrat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 360));

        BtnLihat.setBackground(new java.awt.Color(255, 204, 0));
        BtnLihat.setFont(new java.awt.Font("Quicksand Medium", 1, 12)); // NOI18N
        BtnLihat.setForeground(new java.awt.Color(51, 51, 51));
        BtnLihat.setText("Lihat Data >");
        BtnLihat.setBorderPainted(false);
        BtnLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLihatActionPerformed(evt);
            }
        });
        PnlPilihMK.add(BtnLihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 120, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/katarak/images/output-onlinepngtools.png"))); // NOI18N
        jLabel11.setToolTipText("");
        PnlPilihMK.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 50, 410, 320));

        jPanel3.add(PnlPilihMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 370));

        PnlData.setBackground(new java.awt.Color(255, 255, 255));
        PnlData.setFocusable(false);
        PnlData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Rincian data mahasiswa :");
        PnlData.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 30));

        TblDataMhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TblDataMhs.setEnabled(false);
        jScrollPane1.setViewportView(TblDataMhs);

        PnlData.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 540, 220));

        BtnEditMK.setBackground(new java.awt.Color(255, 204, 0));
        BtnEditMK.setFont(new java.awt.Font("Quicksand Medium", 1, 12)); // NOI18N
        BtnEditMK.setForeground(new java.awt.Color(51, 51, 51));
        BtnEditMK.setText("Edit MK");
        BtnEditMK.setBorderPainted(false);
        BtnEditMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditMKActionPerformed(evt);
            }
        });
        PnlData.add(BtnEditMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, 30));

        BtnHpsMK.setBackground(new java.awt.Color(255, 0, 0));
        BtnHpsMK.setFont(new java.awt.Font("Quicksand Medium", 1, 12)); // NOI18N
        BtnHpsMK.setForeground(new java.awt.Color(255, 255, 255));
        BtnHpsMK.setText("Hapus MK");
        BtnHpsMK.setBorderPainted(false);
        BtnHpsMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHpsMKActionPerformed(evt);
            }
        });
        PnlData.add(BtnHpsMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 110, 30));

        CmbDataMhs.setBackground(new java.awt.Color(204, 204, 204));
        CmbDataMhs.setForeground(new java.awt.Color(51, 51, 51));
        PnlData.add(CmbDataMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 410, 30));

        BtnBukaMhs.setBackground(new java.awt.Color(0, 51, 102));
        BtnBukaMhs.setFont(new java.awt.Font("Quicksand Medium", 1, 12)); // NOI18N
        BtnBukaMhs.setForeground(new java.awt.Color(255, 255, 255));
        BtnBukaMhs.setText("Buka");
        BtnBukaMhs.setBorderPainted(false);
        BtnBukaMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBukaMhsActionPerformed(evt);
            }
        });
        PnlData.add(BtnBukaMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 321, 110, 30));

        BtnTambahMhs.setBackground(new java.awt.Color(51, 51, 51));
        BtnTambahMhs.setFont(new java.awt.Font("Quicksand Medium", 1, 12)); // NOI18N
        BtnTambahMhs.setForeground(new java.awt.Color(255, 255, 255));
        BtnTambahMhs.setText("+ Tambahkan Mahasiswa");
        BtnTambahMhs.setBorderPainted(false);
        BtnTambahMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahMhsActionPerformed(evt);
            }
        });
        PnlData.add(BtnTambahMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 210, -1));

        jLabel10.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Mata Kuliah :");
        PnlData.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        OutputNamaMK.setBackground(new java.awt.Color(255, 255, 255));
        OutputNamaMK.setForeground(new java.awt.Color(0, 0, 0));
        OutputNamaMK.setText("Nama MK");
        OutputNamaMK.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        OutputNamaMK.setEnabled(false);
        PnlData.add(OutputNamaMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 420, 30));

        LblJamSelesai.setFont(new java.awt.Font("Quicksand Medium", 0, 12)); // NOI18N
        LblJamSelesai.setForeground(new java.awt.Color(51, 51, 51));
        LblJamSelesai.setText("Jam Selesai");
        PnlData.add(LblJamSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, -1, -1));

        LblSKS.setFont(new java.awt.Font("Quicksand Medium", 0, 12)); // NOI18N
        LblSKS.setForeground(new java.awt.Color(51, 51, 51));
        LblSKS.setText("SKS");
        PnlData.add(LblSKS, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, -1, -1));

        LblHari.setFont(new java.awt.Font("Quicksand Medium", 0, 12)); // NOI18N
        LblHari.setForeground(new java.awt.Color(51, 51, 51));
        LblHari.setText("Hari");
        PnlData.add(LblHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, -1));

        LblJamMulai.setFont(new java.awt.Font("Quicksand Medium", 0, 12)); // NOI18N
        LblJamMulai.setForeground(new java.awt.Color(51, 51, 51));
        LblJamMulai.setText("Jam Mulai");
        PnlData.add(LblJamMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(255, 204, 0));
        jSeparator3.setForeground(new java.awt.Color(255, 204, 0));
        PnlData.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 210, 10));

        jLabel12.setFont(new java.awt.Font("Quicksand", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Rincian Mata Kuliah");
        PnlData.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Jam Selesai:");
        PnlData.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("SKS:");
        PnlData.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        jLabel15.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Hari Perkuliahan:");
        PnlData.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        jLabel16.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Jam Mulai:");
        PnlData.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, -1));

        jPanel3.add(PnlData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 370));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 800, 370));

        jPanel6.setBackground(new java.awt.Color(255, 204, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnMin.setBackground(new java.awt.Color(255, 204, 0));
        BtnMin.setFont(new java.awt.Font("Quicksand", 1, 12)); // NOI18N
        BtnMin.setForeground(new java.awt.Color(255, 255, 255));
        BtnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/katarak/images/icons8-compress-24.png"))); // NOI18N
        BtnMin.setBorderPainted(false);
        BtnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinActionPerformed(evt);
            }
        });
        jPanel6.add(BtnMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 40, 30));

        BtnLogOut.setBackground(new java.awt.Color(255, 0, 0));
        BtnLogOut.setFont(new java.awt.Font("Quicksand", 1, 12)); // NOI18N
        BtnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogOut.setText("Log Out");
        BtnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogOutActionPerformed(evt);
            }
        });
        jPanel6.add(BtnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 90, 30));

        jLabel9.setFont(new java.awt.Font("Quicksand", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("v1.0");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBukaMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBukaMhsActionPerformed
        Koneksi mhs = new Koneksi();
        String mhspilih = (String) CmbDataMhs.getSelectedItem();
        if(mhspilih=="Tidak ada mahasiswa") {
            JOptionPane.showMessageDialog(null, "Tambahkan dulu mahasiswa!");
        } else {
            mhs.setSelectedMhs(mhspilih);
            new EditMhsPage().setVisible(true);
        }
    }//GEN-LAST:event_BtnBukaMhsActionPerformed

    private void BtnTmbMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTmbMKActionPerformed
        new NewMKPage().setVisible(true);
    }//GEN-LAST:event_BtnTmbMKActionPerformed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        if(CmbMatKul.getSelectedItem()=="Tidak ada mata kuliah") {
            JOptionPane.showMessageDialog(null, "Tambahkan dulu mata kuliah");
        } else {
            Koneksi matkul = new Koneksi();
            String mkpilih = (String) CmbMatKul.getSelectedItem();
            matkul.setSelectedMK(mkpilih);
            new EditMKPage().setVisible(true);
        }
    }//GEN-LAST:event_BtnEditActionPerformed

    private void BtnEditMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditMKActionPerformed
        Koneksi matkul = new Koneksi();
        String mkpilih = (String) CmbMatKul.getSelectedItem();
        matkul.setSelectedMK(mkpilih);
        new EditMKPage().setVisible(true);
    }//GEN-LAST:event_BtnEditMKActionPerformed

    private void BtnHpsMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHpsMKActionPerformed
        Koneksi matkul = new Koneksi();
        String namamk = matkul.getSelectedMK();
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus mata kuliah " + namamk + " ?", "Warning", dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION) {
            try {
                String statone = "DELETE FROM detailmatakuliah WHERE namamk='"+namamk+"'";
                ps = con.prepareStatement(statone);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Mata kuliah berhasil dihapus");
                PnlData.setVisible(false);
                PnlPilihMK.setVisible(true);
                Koneksi panel = new Koneksi();
                String active = "pilihmk";
                panel.setActivePanel(active);
                CmbMatKul.removeAllItems();
                LblNamaUsr.removeAll();
                loadMK();
                loadNama();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan : " + e.getMessage());
            }
        }
    }//GEN-LAST:event_BtnHpsMKActionPerformed

    private void BtnLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLihatActionPerformed
        if(CmbMatKul.getSelectedItem()=="Tidak ada mata kuliah") {
            JOptionPane.showMessageDialog(null, "Tambahkan dulu mata kuliah");
        } else {
            PnlPilihMK.setVisible(false);
            PnlData.setVisible(true);
            Koneksi panel = new Koneksi();
            String active = "data";
            panel.setActivePanel(active);
            String mkpilih = (String) CmbMatKul.getSelectedItem();
            panel.setSelectedMK(mkpilih);
            loadMhsTbl();
            loadMhsCmb();
            loadDetailMK();
            String mkfin = panel.getSelectedMK();
            OutputNamaMK.setText(mkfin);
        }
    }//GEN-LAST:event_BtnLihatActionPerformed

    private void BtnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinActionPerformed
        setState(MainWelPage.ICONIFIED);
    }//GEN-LAST:event_BtnMinActionPerformed

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
        PnlData.setVisible(false);
        Koneksi panel = new Koneksi();
        String active = "pilihmk"; 
        panel.setActivePanel(active);
        panel.setSelectedMK(null);
        PnlPilihMK.setVisible(true);
    }//GEN-LAST:event_BtnHomeActionPerformed

    private void BtnNewAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNewAccActionPerformed
        new NewAccPage().setVisible(true);
    }//GEN-LAST:event_BtnNewAccActionPerformed

    private void BtnNewMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNewMKActionPerformed
        new NewMKPage().setVisible(true);
    }//GEN-LAST:event_BtnNewMKActionPerformed

    private void BtnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogOutActionPerformed
        super.setVisible(false);
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_BtnLogOutActionPerformed

    private void BtnNewMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNewMhsActionPerformed
        if(CmbMatKul.getSelectedItem()=="Tidak ada mata kuliah") {
            JOptionPane.showMessageDialog(null, "Tambahkan dulu mata kuliah, kemudian tambahkan mahasiswa");
        } else {
            new NewMhsPage().setVisible(true);
        }
    }//GEN-LAST:event_BtnNewMhsActionPerformed

    private void BtnTambahMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahMhsActionPerformed
        Koneksi matkul = new Koneksi();
        String mkpilih = (String) CmbMatKul.getSelectedItem();
        matkul.setSelectedMK(mkpilih);
        new NewMhsPage().setVisible(true);
    }//GEN-LAST:event_BtnTambahMhsActionPerformed

    private void BtnFgtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFgtPassActionPerformed
        new FgtPassPage().setVisible(true);
    }//GEN-LAST:event_BtnFgtPassActionPerformed

    private void loadMhsTbl() {
        try {
            Koneksi nip = new Koneksi();
            String mkfin = nip.getSelectedMK();
            String hashfin = nip.getSession();
            String showmhs = "SELECT nim,nama,nohp FROM detailmahasiswa WHERE otoritas='"+hashfin+"' AND matakuliah='"+mkfin+"' ORDER BY nim ASC";
            ps = con.prepareStatement(showmhs);
            rs = ps.executeQuery(showmhs);
            rs.beforeFirst();
            String[] columnNames = {"NIM","Nama","No.HP"};
            DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
            
            while(rs.next()) {
                String nim = rs.getString("nim");
                String nama = rs.getString("nama");
                String nohp = rs.getString("nohp");
                String[] data = {nim,nama,nohp};
                
                tableModel.addRow(data);
            }
            
            TblDataMhs.setModel(tableModel);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void loadMhsCmb() {
        try {
            CmbDataMhs.removeAllItems();
            Koneksi nip = new Koneksi();
            String mkfin = nip.getSelectedMK();
            String hashfin = nip.getSession();
            String showmhs = "SELECT nim,nama,nohp FROM detailmahasiswa WHERE otoritas='"+hashfin+"' AND matakuliah='"+mkfin+"' ORDER BY nim ASC";
            ps = con.prepareStatement(showmhs);
            rs = ps.executeQuery(showmhs);
            rs.beforeFirst();
            
            while(rs.next()) {
                String nim = rs.getString("nim");
                String nama = rs.getString("nama");
                
                String rincian = nim + " - " + nama;
                CmbDataMhs.addItem(rincian);
            }
            
            if(CmbDataMhs.getItemCount()==0) {
                CmbDataMhs.addItem("Tidak ada mahasiswa");
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void loadDetailMK() {
        try {
            Koneksi nip = new Koneksi();
            String hashfin = nip.getSession();
            String mkfin = nip.getSelectedMK();
            String detailmk = "SELECT * FROM detailmatakuliah WHERE otoritas='"+hashfin+"' AND namamk='"+mkfin+"'";
            ps = con.prepareStatement(detailmk);
            rs = ps.executeQuery(detailmk);
            while(rs.next()) {
                String sks = rs.getString("sks");
                LblSKS.setText(sks);
                String hari = rs.getString("hari");
                LblHari.setText(hari);
                String jammulai = rs.getString("jammulai");
                LblJamMulai.setText(jammulai);
                String jamselesai = rs.getString("jamselesai");
                LblJamSelesai.setText(jamselesai);
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan dengan error : " + e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainWelPage().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(MainWelPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBukaMhs;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnEditMK;
    private javax.swing.JButton BtnFgtPass;
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton BtnHpsMK;
    private javax.swing.JButton BtnLihat;
    private javax.swing.JButton BtnLogOut;
    private javax.swing.JButton BtnMin;
    private javax.swing.JButton BtnNewAcc;
    private javax.swing.JButton BtnNewMK;
    private javax.swing.JButton BtnNewMhs;
    private javax.swing.JButton BtnTambahMhs;
    private javax.swing.JButton BtnTmbMK;
    private javax.swing.JComboBox<String> CmbDataMhs;
    private javax.swing.JComboBox<String> CmbMatKul;
    private javax.swing.JLabel LblHari;
    private javax.swing.JLabel LblJamMulai;
    private javax.swing.JLabel LblJamSelesai;
    private javax.swing.JLabel LblNamaUsr;
    private javax.swing.JLabel LblSKS;
    private javax.swing.JTextField OutputNamaMK;
    private javax.swing.JLabel PicSamrat;
    private javax.swing.JPanel PnlData;
    private javax.swing.JPanel PnlPilihMK;
    private javax.swing.JTable TblDataMhs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}