/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package katarak;

import java.awt.Window;
import katarak.utility.Koneksi;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class NewMKPage extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    Statement stat;
    String sql;
    PreparedStatement ps;
    String kode;
    String kelas;
    String sks;
    String nama;
    String hari;
    String jammulai;
    String jamselesai;
    int posX=0,posY=0;
    /**
     * Creates new form NewAccPage
     */
    public NewMKPage() {
        initComponents();
        Koneksi DB = new Koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        
        this.pack();
        this.setLocationRelativeTo(null);
        
        this.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                posX=e.getX();
                posY=e.getY();
            }
        });
        
        this.addMouseMotionListener(new MouseAdapter() {
            public void mouseDragged(MouseEvent evt) {
                setLocation(evt.getXOnScreen()-posX,evt.getYOnScreen()-posY);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        LblNamaMK = new javax.swing.JLabel();
        InputKode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InputKelas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        InputNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BtnSimpan = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        InputJamSelesai = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        InputHari = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        InputSKS = new javax.swing.JComboBox<>();
        InputJamMulai = new javax.swing.JComboBox<>();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buat Akun Baru - Katarak");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/katarak/images/appicon.png")).getImage());
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblNamaMK.setFont(new java.awt.Font("Quicksand", 1, 12)); // NOI18N
        LblNamaMK.setForeground(new java.awt.Color(51, 51, 51));
        LblNamaMK.setText("Mata Kuliah");
        jPanel1.add(LblNamaMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        InputKode.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(InputKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, -1));

        jLabel3.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("SKS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        InputKelas.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(InputKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 160, -1));

        jLabel4.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nama Mata Kuliah");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        InputNama.setBackground(new java.awt.Color(255, 255, 255));
        InputNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputNamaFocusLost(evt);
            }
        });
        jPanel1.add(InputNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 340, -1));

        jLabel5.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Hari");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Quicksand", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Input Mata Kuliah");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnSimpan.setBackground(new java.awt.Color(255, 204, 0));
        BtnSimpan.setFont(new java.awt.Font("Quicksand", 1, 12)); // NOI18N
        BtnSimpan.setForeground(new java.awt.Color(51, 51, 51));
        BtnSimpan.setText("Simpan");
        BtnSimpan.setBorderPainted(false);
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(BtnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 16, -1, -1));

        BtnBatal.setBackground(new java.awt.Color(0, 51, 102));
        BtnBatal.setFont(new java.awt.Font("Quicksand", 1, 12)); // NOI18N
        BtnBatal.setForeground(new java.awt.Color(255, 255, 255));
        BtnBatal.setText("Batal");
        BtnBatal.setBorderPainted(false);
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });
        jPanel2.add(BtnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 16, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 346, 390, 70));

        BtnExit.setBackground(new java.awt.Color(255, 0, 0));
        BtnExit.setFont(new java.awt.Font("Quicksand", 1, 12)); // NOI18N
        BtnExit.setForeground(new java.awt.Color(255, 255, 255));
        BtnExit.setText("X");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        jPanel1.add(BtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Quicksand", 0, 8)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("KATARAK - temuKAn daTa mahasiswA yang mengontRAK");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        InputJamSelesai.setBackground(new java.awt.Color(255, 255, 255));
        InputJamSelesai.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        InputJamSelesai.setForeground(new java.awt.Color(51, 51, 51));
        InputJamSelesai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08.50", "09.40", "10.30", "11.20", "12.10", "13.00", "13.50", "14.40", "15.30", "16.20", "17.10", "18.00" }));
        jPanel1.add(InputJamSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 160, -1));

        jLabel7.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Kelas");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Jam Mulai");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        InputHari.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(InputHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 340, -1));

        jLabel9.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Kode");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel10.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Mata Kuliah :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Jam Selesai");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        InputSKS.setBackground(new java.awt.Color(255, 255, 255));
        InputSKS.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        InputSKS.setForeground(new java.awt.Color(51, 51, 51));
        InputSKS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jPanel1.add(InputSKS, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 70, -1));

        InputJamMulai.setBackground(new java.awt.Color(255, 255, 255));
        InputJamMulai.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        InputJamMulai.setForeground(new java.awt.Color(51, 51, 51));
        InputJamMulai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08.00", "08.50", "09.40", "10.30", "11.20", "12.10", "13.00", "13.50", "14.40", "15.30", "16.20", "17.10" }));
        jPanel1.add(InputJamMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        Koneksi nip = new Koneksi();
        String hashfin = nip.getSession();
        kode = InputKode.getText();
        kelas = InputKelas.getText();
        sks = (String) InputSKS.getSelectedItem();
        nama = InputNama.getText();
        hari = InputHari.getText();
        jammulai = (String) InputJamMulai.getSelectedItem();
        jamselesai = (String) InputJamSelesai.getSelectedItem();
        if(InputKode.getText().equals("") || InputKelas.getText().equals("") || InputNama.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Masukan data dengan lengkap");
        } else {
            try {
                sql = "SELECT * FROM detailmatakuliah WHERE otoritas='"+hashfin+"'";
                rs = stat.executeQuery(sql);
                if (rs.next()) {
                    if(InputKode.getText().equals(rs.getString("kode"))) {
                        JOptionPane.showMessageDialog(null, "Mata kuliah sudah ada");
                    } else {
                        StoreData();
                        this.dispose();
                    }
                } else {
                    StoreData();
                    this.dispose();
                }
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan : " + e.getMessage());
            }
        }
    }//GEN-LAST:event_BtnSimpanActionPerformed

    public void StoreData() {
        Koneksi nip = new Koneksi();
        String hashfin = nip.getSession();
        kode = InputKode.getText();
        kelas = InputKelas.getText();
        sks = (String) InputSKS.getSelectedItem();
        nama = InputNama.getText();
        hari = InputHari.getText();
        jammulai = (String) InputJamMulai.getSelectedItem();
        jamselesai = (String) InputJamSelesai.getSelectedItem();
        try {
            String statone = "INSERT INTO detailmatakuliah values('"+kode+kelas+" - "+nama+"','"+kode+"','"+kelas+"','"+sks+"','"+nama+"','"+hari+"','"+jammulai+"','"+jamselesai+"','"+hashfin+"')";
            ps = con.prepareStatement(statone);
            ps.executeUpdate(statone);
            JOptionPane.showMessageDialog(null, "Mata kuliah berhasil ditambahkan");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan : " + e.getMessage());
        }
    }
    
    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        dispose();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        dispose();
    }//GEN-LAST:event_BtnExitActionPerformed

    private void InputNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputNamaFocusLost
        String namamatkul = InputKode.getText()+InputKelas.getText()+" - "+InputNama.getText();
        LblNamaMK.setText(namamatkul);
    }//GEN-LAST:event_InputNamaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMKPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JTextField InputHari;
    private javax.swing.JComboBox<String> InputJamMulai;
    private javax.swing.JComboBox<String> InputJamSelesai;
    private javax.swing.JTextField InputKelas;
    private javax.swing.JTextField InputKode;
    private javax.swing.JTextField InputNama;
    private javax.swing.JComboBox<String> InputSKS;
    private javax.swing.JLabel LblNamaMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
